name: Continuous Integration
run-name: ${{ github.actor }} pushed to the main branch ğŸš€

on:
  push:
    branches:
    - main

jobs:

  lint:
    name: Validate Code Quality
    runs-on: ubuntu-latest

    steps:
    - name: ğŸµ check, check, check, check out ma melody ğŸµ
      uses: actions/checkout@v3
      with:
        path: main
    - name: Set up Python ğŸ
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3
    - name: Install dependencies
      run: pip install -r main/project/requirements_ci.txt && pip install flake8
    - name: Run Flake8 â„ï¸
      run: flake8 --exclude=venv,__pycache__ --ignore=F405,E501,F401,E241 main/project
    
  test:
    name: Test Code Behaviour
    runs-on: ubuntu-latest
    
    steps:
    - name: ğŸµ check, check, check, check out ma melody ğŸµ
      uses: actions/checkout@v3
      with:
        path: main
    - name: Set up Python ğŸ
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3
    - name: Install dependencies
      run: pip install -r main/project/requirements_ci.txt
    - name: Run the tests
      run: cd main && project/tests.sh
